
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="fromtheshadows" #mandatory

version="${file.jarVersion}" #mandatory
displayName="From the shadows" #mandatory
logoFile="fromtheshadows.png" #optional
authors="Sonmok14" #optional
description='''
Against the evil of ancient evil!
'''
[[dependencies.fromtheshadows]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fromtheshadows]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
